export interface Beneficiary {
  idsolicitud: string;
  numerodedocumento: string;
  fechaexpedicioncc: string;
  primernombre: string;
  segundonombre: string;
  username: string | null;
  genero: string;
  edad: string;
  celular: string;
  residencia: string;
  departamento: string;
  municipio: string;
  situacion: string;
  grupo: string;
  etnias: string;
  rol: string;
  estado: string;
  createdAt: string;
  updatedAt: string;
  idempresa: number | null;
  nit: string;
  nombreempresa: string;
  digitoverificacion: string;
  tipoempresa: string;
  aniofundacion: string;
  actividadeconomica: string;
  activos: string;
  pasivos: string;
  deudas_bancarias: string;
  patrimonio: string;
  municipioempresa: string;
  tieneactividadsostenible: string;
  desarrollaraactividadsostenible: string;
  garantiasreales: string;
  tratamientodedatos: string;
  autorizacioncentralriesgos: string;
  ventas: string;
  empleosgenerado: string;
  empleosagenerar: string;
  economiacircular: string;
  otroeconomiacircular: string | null;
  prioridad: string | null;
  fechasolicitud: string | null;
  estadoempresa: string | null;
  dinerosolicitado: string;
  cuotas: string;
  motivos: string;
  estadocredito: string | null;
  observaciones: string | null;
}
